spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/event_planner
    username: ikram
    password: ikram
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG


